### ISSUE TITLE
docker container does not start

### ISSUE THREAD

**Issue by geekvoice408** [neredera/teslafi_exporter#2]
```
/usr/local/bin/teslafi_exporter:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.util as util
INFO:root:Using TeslaFi API Token: <removed>
Traceback (most recent call last):
  File "/usr/local/bin/teslafi_exporter", line 1021, in <module>
    TESLAFI_COLLECTOR = TeslaFiCollector(teslafi_api_token)
  File "/usr/local/bin/teslafi_exporter", line 32, in __init__
    registry.register(self)
  File "/usr/local/lib/python3.10/site-packages/prometheus_client/registry.py", line 26, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.10/site-packages/prometheus_client/registry.py", line 66, in _get_names
    for metric in desc_func():
  File "/usr/local/bin/teslafi_exporter", line 94, in collect
    self.getSetData(teslafi_data, teslafi_data_old, "vin"),
  File "/usr/local/bin/teslafi_exporter", line 63, in getSetData
    if data_old[key] is None or data_old[key] == '':
KeyError: 'vin'
```

**Comment by brianpham** [comment]
This happens when TeslaFi has not been able to poll any data yet. You can try opening your Tesla app and waiting a few mins so that TeslaFi can try polling data again.
