### ISSUE TITLE
Getting `TypeError: float() argument must be a string or a number, not 'NoneType'` error

### ISSUE THREAD

**Issue by JHamCell** [neredera/teslafi_exporter#5]
I have been using this for a couple of years and out of the blue, I am now getting this error:

`teslafi_exporter@pir0u1:/usr/local/teslafi/teslafi_exporter$` **`/usr/local/teslafi/teslafi_exporter/exporter.py --teslafi_api_token REDACTED`**
```
INFO:root:Using TeslaFi API Token: REDACTED
Traceback (most recent call last):
  File "/usr/local/teslafi/teslafi_exporter/exporter.py", line 1031, in <module>
    TESLAFI_COLLECTOR = TeslaFiCollector(teslafi_api_token)
  File "/usr/local/teslafi/teslafi_exporter/exporter.py", line 32, in __init__
    registry.register(self)
  File "/usr/local/lib/python3.7/dist-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.7/dist-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
  File "/usr/local/teslafi/teslafi_exporter/exporter.py", line 158, in collect
    value=float(self.getSetData(teslafi_data, teslafi_data_old, "odometer"))*1609.344)
TypeError: float() argument must be a string or a number, not 'NoneType'
```
There are no updates here.
Is this the result of a TeslaFi change?
Have I done something stupid without realising it?

**Comment by JHamCell** [comment]
Fixed it.
I had Enabled Tesla Fleet key in TeslaFi, but did not enable the Fleet Telemetry.
Once I enabled that, `teslafi_exporter` started working without error.

**Comment by JHamCell** [comment]
Fixed it.
I had Enabled Tesla Fleet key in TeslaFi, but did not enable the Fleet Telemetry.
Once I enabled that, `teslafi_exporter` started working without error.
